// get user //
export const GET_USER_PENDING = " GET_USER_PENDING"
export const GET_USER_SUCCESS =" GET_USER_SUCCESS"
export const GET_USER_ERROR = " GET_USER_ERROR"

// post user //
export const POST_USER_PENDING = " POST_USER_PENDING"
export const POST_USER_SUCCESS =" POST_USER_SUCCESS"
export const POST_USER_ERROR = " POST_USER_ERROR"

// delete user //

export const DELETE_USER_PENDING = " DELETE_USER_PENDING"
export const DELETE_USER_SUCCESS =" DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = " DELETE_USER_ERROR"

// UPDATE USER//

export const UPDATE_USER_PENDING = " UPDATE_USER_PENDING"
export const UPDATE_USER_SUCCESS =" UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = " UPDATE_USER_ERROR"
